"""Textual research report generator."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from neural_ik.metadata import AUTHOR, PROJECT_NAME, VERSION


def generate_text_report(
    experiment_results: dict[str, Any] | None = None,
    output_path: str | Path | None = None,
) -> str:
    """Generate a plain-text research report skeleton.

    If experiment_results is None or incomplete, the Results section
    explicitly states that numbers have not been generated yet.
    """
    lines = [
        f"# {PROJECT_NAME} — Research Report",
        f"Version: {VERSION}",
        f"Author: {AUTHOR}",
        "",
        "## 1. Research Question",
        "",
        "Can a neural network learn to approximate inverse kinematics for a",
        "robotic manipulator, and how does its performance compare with",
        "conventional analytical and numerical inverse kinematics?",
        "",
        "## 2. Mathematical Formulation",
        "",
        "### Forward Kinematics (2R Planar)",
        "x = L1 cos(θ1) + L2 cos(θ1 + θ2)",
        "y = L1 sin(θ1) + L2 sin(θ1 + θ2)",
        "",
        "### Workspace",
        "|L1 − L2| ≤ √(x² + y²) ≤ L1 + L2",
        "",
        "### Analytical Inverse Kinematics",
        "Geometric solution via the law of cosines with elbow-up / elbow-down branches.",
        "",
        "## 3. Robot Model",
        "Planar 2R manipulator with configurable link lengths and joint limits.",
        "",
        "## 4. Dataset",
        "Generated by sampling joint configurations and applying forward kinematics.",
        "Train / validation / test splits with optional noise injection.",
        "",
        "## 5. Neural Architecture",
        "Configurable MLP mapping (x, y) → (θ1, θ2). Normalization applied.",
        "",
        "## 6. Training Procedure",
        "Supervised MSE on joint angles. Early stopping on validation loss.",
        "",
        "## 7. Baselines",
        "- Analytical geometric IK",
        "- Numerical: Jacobian transpose, pseudoinverse, damped least-squares",
        "",
        "## 8. Evaluation Methodology",
        "Position error after FK of predicted joints. MAE, RMSE, percentiles,",
        "latency, and throughput.",
        "",
        "## 9. Results",
        "",
    ]

    if experiment_results is None:
        lines.append(
            "Results not yet generated. Run the corresponding experiment "
            "to populate this section."
        )
    else:
        lines.append("```")
        lines.append(str(experiment_results))
        lines.append("```")

    lines.extend(
        [
            "",
            "## 10. Error Analysis",
            "See generated error histograms and heatmaps under assets/plots/.",
            "",
            "## 11. Failure Cases",
            "Worst predictions are exported by evaluation scripts for inspection.",
            "",
            "## 12. Limitations",
            "- Single 2R planar arm; higher-DOF arms are future work.",
            "- Multi-solution ambiguity handled by canonical branch selection.",
            "- Neural models may degrade near singularities and workspace boundaries.",
            "",
            "## 13. Conclusions",
            "Conclusions should be drawn only after experiments have been executed.",
            "",
            "## 14. Future Work",
            "- 3R and spatial manipulators",
            "- Uncertainty estimation",
            "- Online adaptation",
            "- Hardware deployment studies",
            "",
        ]
    )

    text = "\n".join(lines)
    if output_path is not None:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return text
